server:
  port: 8081

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true